services:
  prod-bot:
    build: ./
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    profiles: [prod]
    depends_on:
      db:
        condition: service_healthy
        restart: true

  dev-bot:
    build: ./
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    profiles: [dev]
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=bot_data
    volumes:
      - konktils-db:/var/lib/postgresql/data 
      - ./dbinit:/docker-entrypoint-initdb.d/:z
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bot_data"]
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 10s

volumes:
  konktils-db:
