name: Build
on:
  pull_request:
  
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          
  build:
    name: Build, format, and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Check formatting
        run: files="$(gofmt -l ./)" && echo "$files" && test -z "$files"
          
      - name: Go Vet
        if: success() || failure()
        run: go vet ./...
      - name: Go Mod
        if: success() || failure()
        run: go mod download
      - name: Go Mod Verify
        if: success() || failure()
        run: go mod verify
        
      - name: Build
        id: build
        if: success() || failure()
        run: go build -v ./...

      - name: Test
        if: steps.build.outcome == 'success'
        run: go test ./...
