name: Build
on:
  pull_request:
  
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          
  build:
    name: Format and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Create local branch
        run: git checkout -b pr-branch
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
      - name: Gofmt
        run: gofmt -s -w .
      - name: Go Tidy
        run: go mod tidy
      - name: Commit formatting changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: fix formatting"
          push: origin HEAD:${{ github.event.pull_request.head.ref }}
          
      - name: Go Vet
        run: go vet ./...
      - name: Go Mod
        run: go mod download
      - name: Go Mod Verify
        run: go mod verify
        
      - name: Build
        run: go build -o /dev/null ./...
