name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: self-hosted
    environment: "production"

    steps:
      - uses: actions/checkout@v4

      - name: Stop previously running bot
        run: docker stop konkurransetilsynet

      - name: Remove previous bot
        run: docker rm konkurransetilsynet

      - name: Deploy bot
        run: docker compose up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}
