name: Deploy to development

on:
  push:
    branches: [ develop ]

jobs:
  Deploy:
    runs-on: self-hosted
    environment: "development"

    steps:
      - uses: actions/checkout@v4

      - name: Deploy bot
        run: docker compose -f docker-compose_dev.yml up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}
