name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      compose_flag:
        required: false
        type: string

jobs:
  Deploy:
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Run bot
        run: docker compose ${{ inputs.compose_flag }} up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Clean up unused images
        run: docker image prune -f
