name: Deploy to development

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: self-hosted
    environment: "development"

    steps:
      - uses: actions/checkout@v4

      - name: Delete previous deployments
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: "development"
          onlyRemoveDeployments: true

      - name: Deploy bot
        run: docker compose --profile dev up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}
