name: Deploy to development

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: self-hosted
    environment: "development"

    steps:
      - uses: actions/checkout@v4

      - name: Deploy bot
        run: docker compose --profile dev up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
