name: Deploy

on:
  push:
    branches: [ main, develop ]

jobs:
  Deploy:
    runs-on: self-hosted
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/develop' && 'development' }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Run bot
        run: docker compose up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Clean up unused images
        run: docker image prune -f
