name: Deploy to production

on:
  push:
    tags:
      - "**"

jobs:
  Deploy:
    runs-on: self-hosted
    environment: "production"

    steps:
      - uses: actions/checkout@v4

      - name: Deploy bot
        run: docker compose --profile prod up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
